### ISSUE TITLE
Action categories - Primary and secondary, and "Featured Actions" category

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#109]
Currently action categories are set with an action tag.  I would call this the primary category, and it should be unique so there is no double counting of impact.

I suggest we add a "secondary categories" selection, so actions could be associated with multiple categories for filtering.  This would make it easier to find actions through filtering.

Also I think there should be a "Featured Actions" category, which is similar to how CCS does it.  
The idea of this is to deal with the issue of too many actions, which some people have said is a problem.  Showing "Featured Actions" would be the default when a user first arrives at the "Actions" page, just the featured actions show, and the user can check them out and decide whether to look at more actions, or specific to a category though filtering.

**Comment by BradHN1** [comment]
Not sure why this was reopened.  I had decided it wasn't important, but happy to discuss.

**Comment by kaatvds** [comment]
I was just pursuing the long term Wishlist board and found this one intriguing.
