### ISSUE TITLE
Route To Delete User Completely 

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/api#188]
At the moment, when a user chooses "Delete profile" from their page, it is not deleted from the ME backend, it is only deleted from firebase. 
So when I delete my account and try to create a new account with the same I email, I go through the same registration process and fill the page out with my new information, but ME backend gives me back my old information.... Which means, my profile was never deleted. 

So...... a route is needed, so I can send a request from the user page to delete, while I delete from firebase too when the try to "delete profile"

**Comment by BradHN1** [comment]
Not creating a new route, but making users.delete do everything it should
This includes the following:
1. Mark UserProfile is_deleted=true, change email address to prepend "DELETED-YYYYMMDD-" to it
2. If profile_picture, mark that is_deleted=true
3. mark all real_estate_units is_deleted=true
4. if a CommunityMember links to user, mark is_deleted=true
5. if a Team includes on Admins, remove it and notify other admins.  if no other admins notify cadmin
6. if a Team includes in Members, remove it
7. if a TeamMember, mark is_deleted
8. if a CommunityAdminGroup includes, remove it, notify lead cadmin
9. if a UserGroup includes, remove it
10. if an EventAttendee - mark is_deleted=true
11. if a Testimonial by user, mark is_delted=true, notify cadmin
12. mark any UserActionRels is_deleted=true
13. if a Vendor includes as onboarding contact, notify cadmin

The following will be preserved, without consequence, for history:
Messages linked to user
ActivityLog linked to user
DeviceProfiles linked to user
Vendor, Action, Event linked to user


*
