### ISSUE TITLE
Type Object "Team Member" has no attribute "Create" 

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/api#200]
@jkatofsky , do we Know what this is about? 

![Screenshot 2020-10-02 at 4 18 16 AM](https://user-images.githubusercontent.com/26961591/94888518-e0d38300-0468-11eb-8b8d-87f4da4b13f4.png)

**Comment by jkatofsky** [comment]
don't know what it is about specifically, but I'd bet you it's a bug in the `join` method of `team.py` in the API `store` folder @frimpongopoku. That's what's called when the team is joined.

**Comment by BradHN1** [comment]
This was fixed some time ago
