### ISSUE TITLE
Allow CAdmins to organize recurring events

### ISSUE THREAD

**Issue by isha-san** [massenergize/api#287]
Allow CAdmins to organize recurring events weekly (what about monthly? @BradHN1 @kaatvds what do you think)

**Comment by kaatvds** [comment]
clicked on date in admin to change it: failed: cf ticket #637

**Comment by nenadev21** [comment]
Cadmins can add recurring events and they show up as recurrent on the community site. 
The only issue is that the "end date" seems not saving on the admin portal, so unsure if the event will continue being displayed after the desired date. I'll pass this card and create a new issue under the admin project.
