### ISSUE TITLE
Actions are taken by individuals on units

### ISSUE THREAD

**Issue by satra** [massenergize/api#3]
@Opoku-Agyemang - i think this is one issue that is going to require much more work with a traditional postgres schema than a graph schema. i'm not saying it can't be done, but this particular issue links a few different classes to the carbon calculator/goals for both individuals and communities.

- an individual takes an action (e.g., add solar PV). 
- the individual is pointed at adding info about that specific action (e.g., array size, shading, orientation, etc.,.)
- this info is used to calculate the impact of the action.
- since the action is on a specific property, the values of that action are also tied to that property

let me know your thoughts on how you plan to achieve the cross-linking and the additional data that a taken action needs.

**Comment by satra** [comment]
@Opoku-Agyemang - any thoughts or updates here?

**Comment by Opoku-Agyemang** [comment]
Accounted for this with a new model called Actions Taken After explanation given by Satra in Slack
