### ISSUE TITLE
State Reported Data - Not pulling correct field for data downloads

### ISSUE THREAD

**Issue by apowelka** [massenergize/api#300]
State reported data in data downloads - Actions is incorrect. Pulling wrong fields.  Linked to portal issue

Documentation here: https://docs.google.com/document/d/17pT5swpC3C7J4zER006v7p2FczRCwt0EDO_c1-BMgIE/edit 

example:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5cb0ecd7-7fff-7fdd-d407-5bd2e632fe73"><div dir="ltr" style="margin-left:0pt;" align="left">

  | CAdmin Entered | About Us Display | Data Download
-- | -- | -- | --
Wayland - Solar | 289 | 220 | 68

</div></b>
</body>
</html>

**Comment by BradHN1** [comment]
Fixed deployed to Dev and Canary
