### ISSUE TITLE
Relation data input on home page and impact page forms

### ISSUE THREAD

**Issue by kaatvds** [massenergize/api#301]
also need to figure out how relation
1. data on Comm profile > pages > home page form
2. data on Comm profile > pages > imapcts  page form
For the moment the admin needs to add up the pushed data in all the fields on the impacts page form and input that manually on the home page form... COuld be automatic?

**Comment by BradHN1** [comment]
The cadmin will no longer need to do that.  Now specify initial values (generally zero for households and actions).
Attained value of actions is sum of state/vendor reported in the categories + the initial number
Attained value of households is max of state/vendor reported in the categories (a guess) + initial number
Attained carbon footprint reduction is simply the initial value, currently state values carbon reduction not calculated
