### ISSUE TITLE
Separate 'initial' and 'attained' values in goals

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#318]
'Initial' values are the three numbers entered by a cadmin (households, actions, carbon reduction].
'Attained' values include pushed data from the action categories.

The initial and attained values had been added, but we want cadmins to be able to enable/disable including the 'attained' values.

This change goes with corresponding changes in the frontend-portal and admin portal.

**Comment by nenadev21** [comment]
Unsure how to test this card. As far as I can see. Cadmins aren't able to enable/disable these values (through the admin portal - under comm goals/reported data) and I couldn't see a way for end-users to see this distinction on their community portal. @BradHN1 could you please expand on what's expected.
