### ISSUE TITLE
CAN Downloading a Users CSV from the community view creates an html file with "Server Error (500)" instead of a CSV.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/api#327]
This works fine when downloading a CSV from the ALL Users view, but not from the community view.

This one is broken vvv
![Screen Shot 2021-09-30 at 1 13 43 PM Users CSV](https://user-images.githubusercontent.com/15150372/135501272-1fbe27aa-f533-4c9d-8f9e-474c398aabb8.png)

This one works vvv
![Screen Shot 2021-09-30 at 1 26 00 PM](https://user-images.githubusercontent.com/15150372/135503134-9f964b47-5644-49bf-b71a-2dc58679f978.png)

**Comment by BradHN1** [comment]
Problem was related to a bug from the Teams model change.
Instead of filtering by commity_id, need to filter by communities_id, since teams can nnow span multiple communities.
