### ISSUE TITLE
Super Admin downloads broken - All Users & All Communities

### ISSUE THREAD

**Issue by apowelka** [massenergize/api#367]
When logged in as a Super Admin, two data downloads do not work but have different errors. The third, All Actions, is working just fine.

page: https://admin.massenergize.org/
![image](https://user-images.githubusercontent.com/60662056/140396386-6c0935c3-f9bf-4763-b4e0-0ac45d2a3107.png)

ALL USERS - doesn't complete, just keeps spinning circle.
ALL COMMUNITIES - get an html download, not csv

**Comment by BradHN1** [comment]
The all communities download is easy to fix.
The ALL USERS download is already an issue 259, so will be fixed in that ticket.
