### ISSUE TITLE
Implement asynchronous downloads

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#370]
For tasks which may take time like database downloads, respond quickly and do the task asynchronously, sending results by e-mail

**Comment by BradHN1** [comment]
Sam's suggestions: 

Option #1: (easy)
* request comes in,
* handler receives it, calls the service layer in thread and returns immediately  
 
The tread will finish whenever it finishes.  But the endpoint would have returned immediately.  The service function should do the notification  whenever it is done.  Error or success state.

Option #2 (slightly fancier)
*request comes in
*handler receives it
*handler calls service as usual
*service will add the job to a “queue” and return immediately

whenever the queue is scheduled to run, it will notify the user (since we will store who to notify in the queue as well)
Note: what is the queue here?

A. We can create our own model called queue and enqueue as many of these requests as we want and we can have a cron job pop the unhandled queues one by one and process them/
We can use AWS queues if we want as well
we can use some other fancier kinds of queues that other django libraries may offer. eg: https://django-q.readthedocs.io/en/latest/examples.html

**Comment by nocsav** [comment]
Another option: Has anyone looked at Celery for async task processing?
https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

**Comment by BradHN1** [comment]
I’ve read about Celery, and it may be a good option for us.  We have a number of needs for asynchrous tasks, of which the downloads are a small part.  I wrote this one-page document  <https://docs.google.com/document/d/1vz3WbQrdFURwQd_1FgvcOD3nlHQ8Q9XYsMPyc999UhU/edit?usp=sharing>on more general requirements for an asynchromous task queue.  Sam may be working on some of this in the next week.
