### ISSUE TITLE
PROD: changes to forwarded message to team leader

### ISSUE THREAD

**Issue by kaatvds** [massenergize/api#395]
Maybe it failed because it said (in the all team messages list0 that it had already been forwarded?
![Screenshot (648)](https://user-images.githubusercontent.com/30277868/93618776-bd5b0380-f9a5-11ea-8b5a-7f1fabf86f0a.png)

so I choose the next one in the list, listed as not forwarded
![image](https://user-images.githubusercontent.com/30277868/93618894-e2e80d00-f9a5-11ea-933e-9fad7e3758ee.png)
Same issue:
![image](https://user-images.githubusercontent.com/30277868/93618922-eed3cf00-f9a5-11ea-9199-c27a6299b478.png)

**Comment by BradHN1** [comment]
The original issue had been fixed in admin

Fixed the typo "you you" in the message, and forward the modified message from the admin to the team admin
