### ISSUE TITLE
Partner information

### ISSUE THREAD

**Issue by satra** [massenergize/api#4]
we should clarify what pieces should go into this info field:

https://github.com/massenergize/portalBackEnd/blob/master/src/database/models.py#L119

from my recollection, a lot of this was considered essential for a partner to provide. since there are legal relationships being created here, more than the user relationship.

**Comment by Opoku-Agyemang** [comment]
I cross checked with Ellen and Kaat.  They recommend a new model: Vendor.  I am replacing Partner with this new model together with its new structure and fields
