### ISSUE TITLE
Platform Users should have unique user name to enable communication

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#412]
Currently, users are asked for First Name, Last Name, and Preferred Name.

Often they enter a very short preferred name, such that it wouldn't be possible to tell users apart.
In that case, it will cause problems when it becomes possible for users to communicate with others.

This could be fixed by requiring the Preferred Name to be unique, going through and adding a suffix to each, and inviting users to verify that is ok. 

Instead we could take the model of Twitter, create a new field (a "handle"), which we create automatically from @ + First Initial + Last Name + number, and invite user back to platform to change it if they like.  Handles could be changed, but would need to be  non-reusable (except by the same user). 

Once this is implemented in the API, would need to implement display of handle together with name and profile pic on team page and wherever else needed.

**Comment by Davidjwkinghorn** [comment]
We will be replacing "Preferred name" with "User name". When we convert to unique usernames we'll have to do the following as well:
- [ ] Notify users that usernames are now unique, but that they can change their username later. (This is fine as long as users are traceable back to userIDs. In cases of abuse/harassment etc, it's important to be able to know who's doing it. If they're able to escape detection by changing their username that's a very real issue.)
- [ ] Automatically change existing "Profile names" where duplicates exist and make the "User names" a unique version of what they had before.
