### ISSUE TITLE
Back-end Integration with PostMark

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#437]
Currently the email messages sent from the back-end are sent directly through a google API, not using a mail service, which is not supportable in the long run and causes many messages to go to spam.

The [PostMark](https://postmarkapp.com/) mail delivery service should be a reasonable choice for our needs.  

Steps to address this ticket:

1. MassEnergize subscription to PostMark (Done, month free trial -> paid subscription)
2. Understand what services PostMark provides
3. Review requirements documentation on nudges and asynchronous messaging
4. Spec out back-end changes
5. Create and configure PostMark server, sender signature and anything else
6. Migrate html content messages into PostMark templates
7. Back-end support for sending messages via PostMark
8. Back-end support for email templates and customization, for cadmins to review and customize messages
9. Subsequent: Admin front-end support for email templates and customizations (another ticket)

**Comment by Davidjwkinghorn** [comment]
Should we reopen this ticket since we still need to look into template integration and such? Or we could open a new ticket for those features.
