### ISSUE TITLE
RSVP functionality upgrade - automate message to users who RSVP

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#449]
When a user RSVPs for an event, they should receive a message with event information, including zoom link if available.

Cadmins who enable RSVP enable - send user RSVP message, which is customized HTML including Zoom link or any other information.

Ultimately we could add a reminder e-mail, but for now just send it right away.

**Comment by kaatvds** [comment]
This didn't seem to work for me. I didn't get an email. May have to do with #904?
