### ISSUE TITLE
Sending actions, events, testimonials to Sadmin Portal should be in small chunks

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/api#480]
I am not sure how many actions, testimonials, or events  etc. are in the prod database right now, but very soon, It will be a pain to use the admin portal. My **local**(no internet required, just to be clear 🤣 🤣 )  database has like 600 actions and my first load is a TERRIBLE experience even after all the optimisations we have done on the frontend. 
This is because the api sends in ALL 600 actions on first load. That is very BAD, and actually unnecessary IMO. If we could paginate things on the backend or find better ways of sending the data to frontend in small chunks, that would make everything so much better, and definitely put us in a good place for scaling.

**Comment by Davidjwkinghorn** [comment]
We can break up really large query results into batches if we ever need to query a huge amount of data at once. e.g. for downloads. 

I think paginating from the backend could be a very good solution for most cases. I imagine this would be done by modifying queries by the page that's being viewed in the API.
