### ISSUE TITLE
Validate guest users e-mail address using PostMark

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#498]
When soomeone signs on as a Guest, use PostMark to send them a welcome e-mail. 
If the e-mail fails due to bad address, don't create the userprofile.

**Comment by abdullai-t** [comment]
@BradHN1 here are a few things I realized after a long troubleshoot.

-  I receive a success response after sending email with postmark even if the email is invalid. upon checking on postmark, I see the email marked as bounced.
- This could mean that postmark doesn't instantly sends the email but rather places the email task in a queue (not sure).

With these issues, it would be very difficult to validate emails following the postmark route. We could explore an option where guest users are sent emails with some link upon registering to verify the email they entered. This option will make guest signup a bit tedious.

**Comment by Davidjwkinghorn** [comment]
What are you using to check for a valid email, @abdullai-t?

**Comment by abdullai-t** [comment]
postmark

**Comment by Davidjwkinghorn** [comment]
Pystmark or Postmarker? (I think they both have bounce handling).
