### ISSUE TITLE
[Feature] Run Celery Services from Makefile

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/api#516]
**Additional details/context**
To keep development streamlined we should run the needed Celery services from our makefile. This way devs don't have to manually start up the two services themselves.

**Comment by BradHN1** [comment]
@abdullai-t - if what I showed you works for,  I sugest add that to the current PR.

**Comment by BradHN1** [comment]
@abdullai-t - if what I showed you works for,  I sugest add that to the current PR #515 .
