### ISSUE TITLE
[Bug] Canary: Unable to contact community administrator

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#535]
### Describe the bug
From the ContactUs page, I click "Send Message" and nothing happens.

### To Reproduce
1. Go to Contact Community Admin
2. Fill in the form
3. Click "Send Message"
4. Nothing happens

### Expected behavior
The message should be sent

### Screenshots or video
In the console window, I see the message: **admins.messages.add Postmark API Key not provided**

**Comment by abdullai-t** [comment]
I tested with the [this url](https://communities-canary.massenergize.org/) and it worked
<img width="1680" alt="Screenshot 2022-07-12 at 9 48 37 PM" src="https://user-images.githubusercontent.com/42780120/178605487-e8852d3b-09fa-4cec-b392-f39cbba09f11.png">

**Comment by BradHN1** [comment]
This is working now
