### ISSUE TITLE
Uploaded media should have unique URLs, despite having same file names

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#577]
**Describe the bug**
If I upload a picture with the same file name as another picture someone else has uploaded, it replaces that picture with mine.  This is because the file is stored with its file name in S3 bucket.  It gets a separate Media instance in the DB but multiple media instances point to the same file in the S3 bucket.

It is a fine thing for different content to include the same image, if it is really the same image; that shouldn't create a new Media instance.

The filename should have appended to it a unique identifier (perhaps a hash generated from the image).

In addition if there is an image which is derived from another uploaded image, cropped, resolution changed or edited in some way, there should be a link to the primary image maintained.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradHN1** [comment]
@frimpongopoku - I'm fixing this today, but wanted to point out how ugly this bug is.  When you crop an image in the admin portal, it always names the image "new_image" and then overwrites the image for any other images which have been cropped.  Hah!

**Comment by frimpongopoku** [comment]
Ooo thats a sneaky one 😅😅. Thanks for taking that on Brad 🙏.
