### ISSUE TITLE
[Bug] Message emails are not all getting sent.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/api#592]
**Describe the bug**
Kaat reported that emails to inform the community admin of a new message aren't all sending. 

**Expected behavior**
When a user sends a message to the community admin of a community, the primary contact for the community should receive an email to let them know.

The last one of these messages was sent through Postmark on September 15th to the primary contact of Newton (in case this is a by community bug).

**Comment by kaatvds** [comment]
I would give this priority one (engaged users are not being answered)
