### ISSUE TITLE
User workflow

### ISSUE THREAD

**Issue by satra** [massenergize/api#6]
- [ ] View
- [ ] Register
- [ ] Email verification
- [ ] Custom user view of self
- [ ] Profile completion
- [ ] Unit addition
- [ ] Add actions to units
- [ ] View pending actions
- [ ] Complete actions

Additional user tasks
- [ ] Community membership request
- [ ] Community creation (? - will this require superadmin approval) 
- [ ] Team creation

**Comment by Opoku-Agyemang** [comment]
I am tagging Kieran on this.
