### ISSUE TITLE
User nudge for newly scheduled events

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#628]
Implement a nudge to users, enabled with a user-nudge feature flag.

It should be sent according to the user communication preferences, so may go as often as once per day for some users.

The first nudge will just be for new events scheduled.  

Event must be live
Newly made live since the last nudge this user received (model change?)
So no repeating, no accumulated of events already nudged
Events should be listed in order of date. 
Format similar to the community admin events nudge, except no link to admin portal.
The nudge should list up to some number like 5 events, and if there are more new events, leave them for the next nudge.

Below the new events, text (To see all upcoming events for (community), visit the Events Page (link to events page)

Add hyperlink for adjusting communication preferences to outgoing message

The nudge message comes from the Community that a user is a member of, so if they are a member of multiple communities they get multiple nudges.

If there are no new events in the community, no nudge is sent.

**Comment by apowelka** [comment]
good specs on this @BradHN1 

Only thing that I thought of is that if a user is electing communication preferences biweekly, then limiting event number to 5 might be a problem. Maybe we could instead list the events for next comm period? Do we have a monthly choice? If yes, that might be too many.

**Comment by abdullai-t** [comment]
@BradHN1 what about open and shared events should those be added as well or strictly events created by the user's community.

**Comment by BradHN1** [comment]
Just events which have been posted or shared by your home community,

The reason for limiting it to a handful, and if there are more events to see showing a link to see all events on the community site is twofold:

First don’t overwhelm people with too many things, otherwise they won’t read it fully.  If some site decides to share 15 events in a month, that is too much for users attention spans.

Second, give them a reason to come to the community site.

**Comment by apowelka** [comment]
I agree with your 2 reasons to limit # events, Brad.

Suggested edit to "(To see all upcoming events for (community), visit the Events Page (link to events page)"

Just say " Check out more coming events". Hyperlink to events page. But ONLY include if there are events that are not included in the nudge.

**Comment by apowelka** [comment]
open and shared should be in the list as well

**Comment by kaatvds** [comment]
Will send today

**Comment by kaatvds** [comment]
So, after today's meeting, re latest iteration:

- keep the columns
- give the title two lines and if title only takes up one line, center it in the middle of that (two line) space
- make sure all the cards have room for (1) date, time and (2) in person/online
- In text, get rid of comma “check out these coming events, in Energize Wayland!” 
- Change email in text to the contact us email (not [info@energize.org](mailto:info@energize.org))
- Move the “if you would like to change how often you get these emails…” to underneath  “Check out these coming events” 
-  Add a space below all this text
- in cards, center titles (both vertically and horizontally)
- Turn titles into hyperlinks to event - but don’t let it turn blue and underline (is that possible?)
- Change green font to black (not bold)
- Increase font size of  last line: “Check out more upcoming events” by 1.5-2x (keep centered)

**Comment by kaatvds** [comment]
Can sender be the [community’s name] and email (from “basic info” and in footer)?

**Comment by abdullai-t** [comment]
@kaatvds, here is the latest email template
![Screenshot_20230330-102409_Gmail](https://user-images.githubusercontent.com/42780120/229066797-dc1c086d-d949-410b-af6b-be3fbb1c7c5d.jpg)

![IMG_0376](https://user-images.githubusercontent.com/42780120/229066751-4e48e88a-e863-42f7-aa72-88f471bfb319.png)
