### ISSUE TITLE
Tried to reply to a message: Server error

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#70]
ISSUE 1220
Reported on Fri Dec 20 2019 14:14:05 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = High
STATUS = InProgress - Submitted 

Site Url: 

Description:
As Cadmin Tried to reply to a message: it said "Server error"

User Role: Community Admin
Notes: 1 Sam knows: it’s a google thing: suspicion Sam needs to whitelist

**Comment by kaatvds** [comment]
This issue should be in the front end admin project, not here in front end Community project
