### ISSUE TITLE
Change sender signature on nudge emails

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#792]
**User Story.**
As a community admin
I want nudges sent to my users to come from my community
So that users will read them and trust their content

**Additional details/context**
The document [Nudge Email Sender Signatures](https://docs.google.com/document/d/1kmz7_PbLDerBm1JxUGG_tbttXeh4NH-EL5T8sorMCE4/edit?usp=sharing) describes the options of having nudges come from the community and not MassEnergie.

We need to decide on the best option for setting the sender_signature from Admin portal, saving in the API and validating.

**Value added.**
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by BradHN1** [comment]
Addition:
Back end needs to valiate all emails for community contact address:
* using the PostMark API to request validation, which should cause a validation message to be sent
* when it is validated, we need a database field to mark that that contact email is validated
* one more field needed is the email alias.  If that alias isn't set, the alias used would be the Community name.
* That alias needs to be set on Postmark through the API call above.

**Comment by apowelka** [comment]
so let her know what email bounce so she can fix Neon and Resource center
in thinkific

**Comment by BradHN1** [comment]
@abdullai-t - Please finish this ticket with high priority, so it can be tested and released.

If there is a valid sender signature for the community contact, the user events nudge should be sent from that email.
Otherwise, the email should be sent from the address it is currently sent from.
