### ISSUE TITLE
Fix warning about naive datetime for events published_at

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#823]
**Describe the bug**
WIth timezones enabled, time values in database should all have timezones specified.  There was a warning about events.updated_at not haveing timezone set

Solution:
Add a utility routine local_time() to provide the current time with local time zone

**Comment by archx3** [comment]
@BradHN1 Has the fix for this ticket been deployed to prod?

**Comment by BradHN1** [comment]
I can see that it was, now that I check.  

However, there are a couple of other places in the API code which still give the warning about naive datetimes being used, for example:

messages.ListScheduled:
/opt/anaconda3/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Message.scheduled_at received a naive datetime (2024-02-02 21:49:54.024526) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"

summary.next.steps.forAdmins:
/opt/anaconda3/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField Footage.created_at received a naive datetime (2024-02-02 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
/opt/anaconda3/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField UserProfile.created_at received a naive datetime (2024-02-16 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "

I don’t know whether these messages are important
