### ISSUE TITLE
Add Handler Mock tests

### ISSUE THREAD

**Issue by Opoku-Agyemang** [massenergize/api#90]

**Comment by Davidjwkinghorn** [comment]
@Opoku-Agyemang what's the status on this? There are a few of these mocking tickets that need either closing out or updating.

**Comment by BradHN1** [comment]
If this refers to the Django unit tests, we have partial coverage.  Test procedures are still needed for:
admin, auth, goal, message, page_settings, policy, subscriber, summary, tag_collection, tag, task_queue
