### ISSUE TITLE
Feature - User Nudge Reporting

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#919]
**User Story.**
As a Community Admin
I want to receive an accurate reporting of user **nudge delivery**, **open and click rates**
So that I better understand the impact of these nudge emails

**Additional details/context**
The PostMark server retains information on all message sent for 45 days, and allows exporting such information but only up to 500 records.  To get more complete, summarized information, we would need to use the PostMark API and code up a summary report.

We can implement a routine to produce such a report  for default the last 30 days (choose time interval between 1 and 45 days), which would contain the following information:

1. Number of nudge emails sent to users from the community
2. Number of emails opened by unique users (which is less than the total number of opens, since some users open emails multiple times).  If 3 emails were sent to a user, and the user opened each multiple times, the number of opens should be 3.
3. Number of delivery failures (bounces)
4. Number of spam complaints
5. Number of clicks on content in emails (events in the currently implemented nudge)
6. Number of clicks to change communication preferences
7. Number of actual unsubscribes

**nudge report download from** 

This report could be requested as a download form the admin portal, and also could be sent as a monthly nudge to CAdmins
which they could choose to receive or not.  (_some admin work required_)

**Value added.**
What do you think the value of adding this feature is? (Help managers and developers know how this should be prioritized.)

**Acceptance criteria.**
_The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out._

- [ ] The system should accurately track and report the number of nudge emails sent to users from a community.
- [ ] The system should accurately track and report the number of emails opened by unique users.
- [ ] The system should accurately track and report the number of delivery failures (bounces).
- [ ] The system should accurately track and report the number of spam complaints.
- [ ] The system should accurately track and report the number of clicks on content in emails (events in the currently implemented nudge).
- [ ] The system should accurately track and report the number of clicks to change communication preferences.
- [ ] The system should accurately track and report the number of actual unsubscribes

**Comment by apowelka** [comment]
I really like the idea of an automated report. Is this something that requires coding? Or is Postmark like bitly in that you could create reports and automate them, more like google analytics? ie, don't need a software engineer but need someone to actually get to doing it and maintaining it (Google analytics reports broke this month and I havne't had time to fix it yet)

**Comment by BradHN1** [comment]
No, you have to code it with their API.  Not difficult, I think it should take a couple days of coding.

**Comment by abdullai-t** [comment]
@BradHN1, would you prefer this to run as a task or implement it similarly to the data download feature?

**Comment by BradHN1** [comment]
@abdullai-t - Ideally it would be both a download and a monthly task.  As a download, the admin could specify the time interval, up to 45 days in the past since that is all that Postmark keeps.  As a nudge, it should be for the previous month that ended.

**Comment by abdullai-t** [comment]
Thanks.
