### ISSUE TITLE
User events nudge failis

### ISSUE THREAD

**Issue by BradHN1** [massenergize/api#961]
**Describe the bug**
The user events nudge is failing since recent changes were deployed.
The reason is that EventNudgeSettings doesn't exist in general, though the code assumes it does and accesses it without checking.

In general the EventNudgeSetting witll have default values, so doesn't need to be saved to database.  The suggested fix is to create an EventNugeSetting temporarily with default settings, and use that.

**Comment by BradHN1** [comment]
I have made this suggested change in the branch BHN-nudgefix.
@abdullai-t - could you review and test this.  If working in dev should go to Canary and test the user event nudge there, then apply the fix to prod.

**Comment by abdullai-t** [comment]
> I have made this suggested change in the branch BHN-nudgefix. @abdullai-t - could you review and test this. If working in dev should go to Canary and test the user event nudge there, then apply the fix to prod.

Thanks, @BradHN1 for the quick fix! I've made a PR with your changes and will test it once merged and deployed to Dev.

**Comment by BradHN1** [comment]
Because the nudge task crashed probably on the first event it encountered, you should also add an exception handler into that loop, and notify the slack channel with the information to figure out what event or user data caised tje fao;ire
