### ISSUE TITLE
UI Design for carbon calculator

### ISSUE THREAD

**Issue by archx3** [massenergize/api#969]
### **DESCRIPTION**
Parent ticket : https://github.com/massenergize/frontend-admin/issues/1119

###### UX Design
Insert figma link or link to design

###### Technical Considerations
Insert technical considerations

**Comment by BradHN1** [comment]
Is this a duplicate to Admin 1119?

**Comment by frimpongopoku** [comment]
> Is this a duplicate to Admin 1119?

@BradHN1  when you break down Admin #1119 into its core parts, this is one aspect of it. This ticket is only focused on the experience (UI/UX) design. When the design is complete and approved, there will be another ticket that will be used to track it's implementation.

**Comment by apowelka** [comment]
Hi @frimpongopoku - so, there are three drop-downs that are needed. First a CAdmin selects a Category. Based upon that category, they select a Subcategory. and finally, in a 3rd drop-down, they select an Action. So the mock-up needs another level of drop-down https://www.figma.com/design/KxSrPKXRPaIqjWm0JXLoyf/ME-SignIn-Flows?node-id=812-2 . And, critically, each drop-down must filter based upon former selected item if selected. But also be able to be used independently.

Example: Category - select Solar. then sub-category options to display include: Renewable Electricity, Solar, and Time of Use. Select Solar and the options will include: Community solar, carport solar, rooftop solar, tracking solar.

Here is the document with more detailed specs on these relationships: https://docs.google.com/document/d/1pDezqZ5MbkHcst2nOhuoI9ckf17AnN1WbW5yzIBNE3w/edit
