### ISSUE TITLE
Checks for subscribed users on campaigns

### ISSUE THREAD

**Issue by boatengjephthah27** [massenergize/api#994]
### **Description:**

When a user is subscribing to a community, the user needs to select the community they are from and wants to subscribe to.

### **Steps to Reproduce:**

1. Visit a massEnergize campaign
2. Scroll to the footer and click on the "Subscribe to our Newsletter"

**Expected Result:**

1. When the popup shows no community is chosen at the start, but when you type in the mail and submit, it should alert you to choose a community and if it is other, it should request you add the community name.
2. When a user is already subscribed to a community, and tries subscribing to the same community, the user should be prompted that they have already subscribed to that community

**Actual Result:**

1. When the popup shows no community is chosen at the start, but when you type in the mail and submit, it gives a success response (currently it is assumed that with no community, the default is "*Other*" and the community names gets set to null. (This can be an issue because how will the person receive updates and from which community?)
2. When a user is already subscribed to a community, and tries subscribing to the same community, the response returned is the same as the success response on a first subscription

### **Additional Information:**

https://github.com/massenergize/massenergize-campaigns/assets/104381959/6eca6a2e-81aa-47ed-977e-76711abe1627

**Comment by apowelka** [comment]
I do not think this is a priority, I would much rather some other features be worked on if this is going to take more time.
